- name: archive reactive built charm
  when: needs_charm_build and charm_build_output.rc == 0 and build_type == "reactive"
  register: charm_archived_reactive
  args:
    chdir: "{{ zuul.project.src_dir }}"
    executable: /bin/bash
  shell: |
    tar -cjf {{ charm_build_name }}-{{ zuul.buildset }}.tar.bz2 -C build/builds/{{ charm_build_name }} .
- name: archive charmcraft built charm
  when: needs_charm_build and charm_build_output.rc == 0 and build_type == "charmcraft"
  register: charm_archived_charmcraft
  args:
    chdir: "{{ zuul.project.src_dir }}"
    executable: /bin/bash
  shell: |
    TMP_DIR="/tmp/{{ zuul.buildset }}"
    mkdir $TMP_DIR
    tar -cjf $TMPDIR/{{ charm_build_name }}-{{ zuul.buildset }}.tar.bz2 --exclude='.tox' --exclude='.git' --exclude='build' --exclude='*.tar.bz2' .
    mv $TMPDIR/{{ charm_build_name }}-{{ zuul.buildset }}.tar.bz2 .
    rmdir $TMPDIR
- name: fetch built charm
  when: needs_charm_build and (
          (charm_archived_reactive.rc is defined and charm_archived_reactive.rc == 0) or
          (charm_archived_charmcraft.rc is defined and charm_archived_charmcraft.rc == 0))
  synchronize:
    dest: "{{ zuul.executor.log_root }}"
    mode: pull
    src: "{{ zuul.project.src_dir }}/{{ charm_build_name }}-{{ zuul.buildset }}.tar.bz2"
    verify_host: true
    owner: no
    group: no
- name: Upload built charm to swift
  delegate_to: localhost
  when: needs_charm_build and (
          (charm_archived_reactive.rc is defined and charm_archived_reactive.rc == 0) or
          (charm_archived_charmcraft.rc is defined and charm_archived_charmcraft.rc == 0))
  zuul_swift_upload:
    cloud: "{{ serverstack_cloud }}"
    partition: "false"
    container: "zuul-built-charms"
    public: "yes"
    prefix: ""
    indexes: "false"
    files:
      - "{{ zuul.executor.log_root }}/{{ charm_build_name }}-{{ zuul.buildset }}.tar.bz2"
    delete_after: "2592000"
  register: upload_results

- block:
    - name: Return charm to Zuul
      delegate_to: localhost
      zuul_return:
        data:
          zuul:
            artifacts:
            - name: built charm tarball
              type: charm
              url: http://10.245.161.162:80/swift/v1/zuul/artifacts/built_charms/{{ charm_build_name }}-{{ zuul.buildset }}.tar.bz2
    - name: Print upload failures
      debug:
        var: upload_results.upload_failures
  when: upload_results is defined
