- name: Check for charmcraft file
  when: charm_build_output.rc == 0
  stat:
    path: "{{ zuul.project.src_dir }}/{{ charm_build_name }}.charm"
  register: charmcraft_file

- name: Check for reactive directory
  when: charm_build_output.rc == 0
  stat:
    path: "{{ zuul.project.src_dir }}/build/builds/{{ charm_build_name }}"
  register: reactive_dir

- name: archive reactive built charm
  when: charm_build_output.rc == 0 and reactive_dir.stat.exists
  register: charm_archived
  args:
    chdir: "{{ zuul.project.src_dir }}"
    executable: /bin/bash
  shell: |
    tar -cjf {{ charm_build_name }}-{{ zuul.buildset }}.tar.bz2 -C build/builds/{{ charm_build_name }} .

- name: archive charmcraft built charm
  when: charm_build_output.rc == 0 and charmcraft_file.stat.exists
  register: charm_archived
  args:
    chdir: "{{ zuul.project.src_dir }}"
    executable: /bin/bash
  shell: |
    tar -cjf {{ charm_build_name }}-{{ zuul.buildset }}.tar.bz2 --exclude='.tox' --exclude='.git' --exclude='build'  .

- name: fetch built charm
  synchronize:
    dest: "{{ zuul.executor.log_root }}"
    mode: pull
    src: "{{ zuul.project.src_dir }}/{{ charm_build_name }}-{{ zuul.buildset }}.tar.bz2"
    verify_host: true
    owner: no
    group: no

- name: Upload built charm to swift
  delegate_to: localhost
  when: charm_archived.rc == 0
  zuul_swift_upload:
    cloud: "{{ serverstack_cloud }}"
    partition: "false"
    container: "zuul-built-charms"
    public: "yes"
    prefix: ""
    indexes: "false"
    files:
      - "{{ zuul.executor.log_root }}/{{ charm_build_name }}-{{ zuul.buildset }}.tar.bz2"
    delete_after: "2592000"
  register: upload_results

- block:
    - name: Return charm to Zuul
      delegate_to: localhost
      zuul_return:
        data:
          zuul:
            artifacts:
            - name: built charm tarball
              type: charm
              url: http://10.245.161.162:80/swift/v1/zuul/artifacts/built_charms/{{ charm_build_name }}-{{ zuul.buildset }}.tar.bz2
    - name: Print upload failures
      debug:
        var: upload_results.upload_failures
  when: upload_results is defined
